import productUrl from '../images/pc-slider-temp.jfif';
import mailIcon from '../../../assets/images/icons/mail-icon.svg';
export const connectedTableData = [
    {
        id: 1,
        productUrl: productUrl,
        brandName: '1Store',
        productCategory: 'Home & Garden,',
        brandValues: 'Handmade, Made in Canada',
        status: 'Not Connected',
        btn: (
            <button className="button button-dark connect-brand">
                Connect
            </button>
        ),
        icon: mailIcon,
    },
    {
        id: 2,
        productUrl: productUrl,
        brandName: '2Store',
        productCategory: 'Home & Garden,',
        brandValues: 'Handmade, Made in Canada',
        status: 'Connected',
        icon: mailIcon,
    },
    {
        id: 3,
        productUrl: productUrl,
        brandName: '1Store',
        productCategory: 'Home & Garden,',
        brandValues: 'Handmade, Made in Canada',
        status: 'Pending',
        icon: mailIcon,
    },
    {
        id: 4,
        productUrl: productUrl,
        brandName: '3Store',
        productCategory: 'Home & Garden,',
        brandValues: 'Handmade, Made in Canada',
        status: 'Declined',
        icon: mailIcon,
    },
    {
        id: 5,
        productUrl: productUrl,
        brandName: '3Store',
        productCategory: 'Home & Garden,',
        brandValues: 'Handmade, Made in Canada',
        status: 'Connected',
        icon: mailIcon,
    },
    {
        id: 6,
        productUrl: productUrl,
        brandName: '4Store',
        productCategory: 'Home & Garden,',
        brandValues: 'Handmade, Made in Canada',
        status: 'Connected',
        icon: mailIcon,
    },
    {
        id: 7,
        productUrl: productUrl,
        brandName: '4Store',
        productCategory: 'Home & Garden,',
        brandValues: 'Handmade, Made in Canada',
        status: 'Connected',
        icon: mailIcon,
    },
    {
        id: 8,
        productUrl: productUrl,
        brandName: '5Store',
        productCategory: 'Home & Garden,',
        brandValues: 'Handmade, Made in Canada',
        status: 'Connected',
        icon: mailIcon,
    },
    {
        id: 9,
        productUrl: productUrl,
        brandName: '6Store',
        productCategory: 'Home & Garden,',
        brandValues: 'Handmade, Made in Canada',
        status: 'Connected',
        icon: mailIcon,
    },
    {
        id: 10,
        productUrl: productUrl,
        brandName: '8Store',
        productCategory: 'Home & Garden,',
        brandValues: 'Handmade, Made in Canada',
        status: 'Connected',
        icon: mailIcon,
    },
];
