import mailIcon from '../../../assets/images/icons/mail-icon.svg';
import productUrl from '../images/pc-slider-temp.jfif';
import summer from '../.././Retailer/images/pc-slider-temp.jfif';
import Stock from '../.././Retailer/images/product-stock.png';

export const connectedTableData = [
  {
    id: 1,
    productUrl: productUrl,
    brandName: '1Store',
    productCategory: 'Home & Garden,',
    brandValues: 'Handmade, Made in Canada',
    status: 'Not Connected',
    btn: <button className="button button-dark connect-brand">Connect</button>,
    icon: mailIcon,
  },
  {
    id: 2,
    productUrl: productUrl,
    brandName: '2Store',
    productCategory: 'Home & Garden,',
    brandValues: 'Handmade, Made in Canada',
    status: 'Connected',
    icon: mailIcon,
  },
  {
    id: 3,
    productUrl: productUrl,
    brandName: '1Store',
    productCategory: 'Home & Garden,',
    brandValues: 'Handmade, Made in Canada',
    status: 'Pending',
    icon: mailIcon,
  },
  {
    id: 4,
    productUrl: productUrl,
    brandName: '3Store',
    productCategory: 'Home & Garden,',
    brandValues: 'Handmade, Made in Canada',
    status: 'Declined',
    icon: mailIcon,
  },
  {
    id: 5,
    productUrl: productUrl,
    brandName: '3Store',
    productCategory: 'Home & Garden,',
    brandValues: 'Handmade, Made in Canada',
    status: 'Connected',
    icon: mailIcon,
  },
  {
    id: 6,
    productUrl: productUrl,
    brandName: '4Store',
    productCategory: 'Home & Garden,',
    brandValues: 'Handmade, Made in Canada',
    status: 'Connected',
    icon: mailIcon,
  },
  {
    id: 7,
    productUrl: productUrl,
    brandName: '4Store',
    productCategory: 'Home & Garden,',
    brandValues: 'Handmade, Made in Canada',
    status: 'Connected',
    icon: mailIcon,
  },
  {
    id: 8,
    productUrl: productUrl,
    brandName: '5Store',
    productCategory: 'Home & Garden,',
    brandValues: 'Handmade, Made in Canada',
    status: 'Connected',
    icon: mailIcon,
  },
  {
    id: 9,
    productUrl: productUrl,
    brandName: '6Store',
    productCategory: 'Home & Garden,',
    brandValues: 'Handmade, Made in Canada',
    status: 'Connected',
    icon: mailIcon,
  },
  {
    id: 10,
    productUrl: productUrl,
    brandName: '8Store',
    productCategory: 'Home & Garden,',
    brandValues: 'Handmade, Made in Canada',
    status: 'Connected',
    icon: mailIcon,
  },
];

export const retailerProductData = [
  {
      id: 1,
      status: 'Connected',
      retailerProUrl: summer,
      name: '1Activities Chips for Kids ps for Kids',
      wsp: 'WSP',
      wspPrice: `${10}-${15}`,
      msrp: 'MSRP',
      msrpPrice: `${30}-${50}`,
      icon: Stock,
      text: 'The Idea Box Kids The Idea Box KidsThe Idea Box KidsThe Idea Box Kids Box Kids',
  },
  {
      id: 2,
      status: 'Pending',
      retailerProUrl: summer,
      name: '2Activities Chips for Kids ps for Kids',
      wsp: 'WSP',
      wspPrice: `${10}-${15}`,
      msrp: 'MSRP',
      msrpPrice: `${30}-${50}`,
      icon: Stock,
      text: 'The Idea Box Kids The Idea Box KidsThe Idea Box KidsThe Idea Box Kids Box Kids',
  },
  {
      id: 3,
      status: 'Not Connected',
      retailerProUrl: summer,
      name: '3Activities Chips for Kids ps for Kids',
      wsp: 'WSP',
      wspPrice: `${10}-${15}`,
      msrp: 'MSRP',
      msrpPrice: `${30}-${50}`,
      icon: Stock,
      text: 'The Idea Box Kids The Idea Box KidsThe Idea Box KidsThe Idea Box Kids Box Kids',
  },
  {
      id: 4,
      status: 'Connected',
      retailerProUrl: summer,
      name: '4Activities Chips for Kids ps for Kids',
      wsp: 'WSP',
      wspPrice: `${10}-${15}`,
      msrp: 'MSRP',
      msrpPrice: `${30}-${50}`,
      icon: Stock,
      text: 'The Idea Box Kids The Idea Box KidsThe Idea Box KidsThe Idea Box Kids Box Kids',
  },
  {
      id: 5,
      status: 'Pending',
      retailerProUrl: summer,
      name: '5Activities Chips for Kids ps for Kids',
      wsp: 'WSP',
      wspPrice: `${10}-${15}`,
      msrp: 'MSRP',
      msrpPrice: `${30}-${50}`,
      icon: Stock,
      text: 'The Idea Box Kids The Idea Box KidsThe Idea Box KidsThe Idea Box Kids Box Kids',
  },
  {
      id: 6,
      status: 'Not Connected',
      retailerProUrl: summer,
      name: 'Activities Chips for Kids ps for Kids',
      wsp: 'WSP',
      wspPrice: `${10}-${15}`,
      msrp: 'MSRP',
      msrpPrice: `${30}-${50}`,
      icon: Stock,
      text: 'The Idea Box Kids The Idea Box KidsThe Idea Box KidsThe Idea Box Kids Box Kids',
  },
  {
      id: 7,
      status: 'Connected',
      retailerProUrl: summer,
      name: 'Activities Chips for Kids ps for Kids',
      wsp: 'WSP',
      wspPrice: `${10}-${15}`,
      msrp: 'MSRP',
      msrpPrice: `${30}-${50}`,
      icon: Stock,
      text: 'The Idea Box Kids The Idea Box KidsThe Idea Box KidsThe Idea Box Kids Box Kids',
  },
  {
      id: 8,
      status: 'Pending',
      retailerProUrl: summer,
      name: 'Activities Chips for Kids ps for Kids',
      wsp: 'WSP',
      wspPrice: `${10}-${15}`,
      msrp: 'MSRP',
      msrpPrice: `${30}-${50}`,
      icon: Stock,
      text: 'The Idea Box Kids The Idea Box KidsThe Idea Box KidsThe Idea Box Kids Box Kids',
  },
];
