// Auth
export const IS_SIGN_UP = 'IS_SIGN_UP';
export const IS_SIGN_IN = 'IS_SIGN_IN';

// Profile
export const USER_DETAILS = 'USER_DETAILS';
export const IS_USER_ROLE_UPDATED = 'IS_USER_ROLE_UPDATED';
export const IS_USER_PLATFORM_UPDATED = 'IS_USER_PLATFORM_UPDATED';
export const IS_BRAND_PROFILE_UPDATED = 'IS_BRAND_PROFILE_UPDATED';
export const IS_RETAILER_PROFILE_UPDATED = 'IS_RETAILER_PROFILE_UPDATED';

// Clear Reducer
export const CLEAR_AUTH_REDUCER = 'CLEAR_AUTH_REDUCER';
export const CLEAR_USER_REDUCER = 'CLEAR_USER_REDUCER';
