export default [
  { name: 'AFGHANISTAN', id: 'AF' },
  { name: 'ÅLAND ISLANDS', id: 'AX' },
  { name: 'ALBANIA', id: 'AL' },
  { name: 'ALGERIA', id: 'DZ' },
  { name: 'AMERICAN SAMOA', id: 'AS' },
  { name: 'ANDORRA', id: 'AD' },
  { name: 'ANGOLA', id: 'AO' },
  { name: 'ANGUILLA', id: 'AI' },
  { name: 'ANTARCTICA', id: 'AQ' },
  { name: 'ANTIGUA AND BARBUDA', id: 'AG' },
  { name: 'ARGENTINA', id: 'AR' },
  { name: 'ARMENIA', id: 'AM' },
  { name: 'ARUBA', id: 'AW' },
  { name: 'AUSTRALIA', id: 'AU' },
  { name: 'AUSTRIA', id: 'AT' },
  { name: 'AZERBAIJAN', id: 'AZ' },
  { name: 'BAHAMAS', id: 'BS' },
  { name: 'BAHRAIN', id: 'BH' },
  { name: 'BANGLADESH', id: 'BD' },
  { name: 'BARBADOS', id: 'BB' },
  { name: 'BELARUS', id: 'BY' },
  { name: 'BELGIUM', id: 'BE' },
  { name: 'BELIZE', id: 'BZ' },
  { name: 'BENIN', id: 'BJ' },
  { name: 'BERMUDA', id: 'BM' },
  { name: 'BHUTAN', id: 'BT' },
  { name: 'BOLIVIA, PLURINATIONAL STATE OF', id: 'BO' },
  { name: 'BOSNIA AND HERZEGOVINA', id: 'BA' },
  { name: 'BOTSWANA', id: 'BW' },
  { name: 'BOUVET ISLAND', id: 'BV' },
  { name: 'BRAZIL', id: 'BR' },
  { name: 'BRITISH INDIAN OCEAN TERRITORY', id: 'IO' },
  { name: 'BRUNEI DARUSSALAM', id: 'BN' },
  { name: 'BULGARIA', id: 'BG' },
  { name: 'BURKINA FASO', id: 'BF' },
  { name: 'BURUNDI', id: 'BI' },
  { name: 'CAMBODIA', id: 'KH' },
  { name: 'CAMEROON', id: 'CM' },
  { name: 'CANADA', id: 'CA' },
  { name: 'CAPE VERDE', id: 'CV' },
  { name: 'CAYMAN ISLANDS', id: 'KY' },
  { name: 'CENTRAL AFRICAN REPUBLIC', id: 'CF' },
  { name: 'CHAD', id: 'TD' },
  { name: 'CHILE', id: 'CL' },
  { name: 'CHINA', id: 'CN' },
  { name: 'CHRISTMAS ISLAND', id: 'CX' },
  { name: 'COCOS (KEELING) ISLANDS', id: 'CC' },
  { name: 'COLOMBIA', id: 'CO' },
  { name: 'COMOROS', id: 'KM' },
  { name: 'CONGO', id: 'CG' },
  { name: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', id: 'CD' },
  { name: 'COOK ISLANDS', id: 'CK' },
  { name: 'COSTA RICA', id: 'CR' },
  { name: "CÔTE D'IVOIRE", id: 'CI' },
  { name: 'CROATIA', id: 'HR' },
  { name: 'CUBA', id: 'CU' },
  { name: 'CYPRUS', id: 'CY' },
  { name: 'CZECH REPUBLIC', id: 'CZ' },
  { name: 'DENMARK', id: 'DK' },
  { name: 'DJIBOUTI', id: 'DJ' },
  { name: 'DOMINICA', id: 'DM' },
  { name: 'DOMINICAN REPUBLIC', id: 'DO' },
  { name: 'ECUADOR', id: 'EC' },
  { name: 'EGYPT', id: 'EG' },
  { name: 'EL SALVADOR', id: 'SV' },
  { name: 'EQUATORIAL GUINEA', id: 'GQ' },
  { name: 'ERITREA', id: 'ER' },
  { name: 'ESTONIA', id: 'EE' },
  { name: 'ETHIOPIA', id: 'ET' },
  { name: 'FALKLAND ISLANDS (MALVINAS)', id: 'FK' },
  { name: 'FAROE ISLANDS', id: 'FO' },
  { name: 'FIJI', id: 'FJ' },
  { name: 'FINLAND', id: 'FI' },
  { name: 'FRANCE', id: 'FR' },
  { name: 'FRENCH GUIANA', id: 'GF' },
  { name: 'FRENCH POLYNESIA', id: 'PF' },
  { name: 'FRENCH SOUTHERN TERRITORIES', id: 'TF' },
  { name: 'GABON', id: 'GA' },
  { name: 'GAMBIA', id: 'GM' },
  { name: 'GEORGIA', id: 'GE' },
  { name: 'GERMANY', id: 'DE' },
  { name: 'GHANA', id: 'GH' },
  { name: 'GIBRALTAR', id: 'GI' },
  { name: 'GREECE', id: 'GR' },
  { name: 'GREENLAND', id: 'GL' },
  { name: 'GRENADA', id: 'GD' },
  { name: 'GUADELOUPE', id: 'GP' },
  { name: 'GUAM', id: 'GU' },
  { name: 'GUATEMALA', id: 'GT' },
  { name: 'GUERNSEY', id: 'GG' },
  { name: 'GUINEA', id: 'GN' },
  { name: 'GUINEA-BISSAU', id: 'GW' },
  { name: 'GUYANA', id: 'GY' },
  { name: 'HAITI', id: 'HT' },
  { name: 'HEARD ISLAND AND MCDONALD ISLANDS', id: 'HM' },
  { name: 'HOLY SEE (VATICAN CITY STATE)', id: 'VA' },
  { name: 'HONDURAS', id: 'HN' },
  { name: 'HONG KONG', id: 'HK' },
  { name: 'HUNGARY', id: 'HU' },
  { name: 'ICELAND', id: 'IS' },
  { name: 'INDIA', id: 'IN' },
  { name: 'INDONESIA', id: 'ID' },
  { name: 'IRAN, ISLAMIC REPUBLIC OF', id: 'IR' },
  { name: 'IRAQ', id: 'IQ' },
  { name: 'IRELAND', id: 'IE' },
  { name: 'ISLE OF MAN', id: 'IM' },
  { name: 'ISRAEL', id: 'IL' },
  { name: 'ITALY', id: 'IT' },
  { name: 'JAMAICA', id: 'JM' },
  { name: 'JAPAN', id: 'JP' },
  { name: 'JERSEY', id: 'JE' },
  { name: 'JORDAN', id: 'JO' },
  { name: 'KAZAKHSTAN', id: 'KZ' },
  { name: 'KENYA', id: 'KE' },
  { name: 'KIRIBATI', id: 'KI' },
  { name: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", id: 'KP' },
  { name: 'KOREA, REPUBLIC OF', id: 'KR' },
  { name: 'KUWAIT', id: 'KW' },
  { name: 'KYRGYZSTAN', id: 'KG' },
  { name: "LAO PEOPLE'S DEMOCRATIC REPUBLIC", id: 'LA' },
  { name: 'LATVIA', id: 'LV' },
  { name: 'LEBANON', id: 'LB' },
  { name: 'LESOTHO', id: 'LS' },
  { name: 'LIBERIA', id: 'LR' },
  { name: 'LIBYAN ARAB JAMAHIRIYA', id: 'LY' },
  { name: 'LIECHTENSTEIN', id: 'LI' },
  { name: 'LITHUANIA', id: 'LT' },
  { name: 'LUXEMBOURG', id: 'LU' },
  { name: 'MACAO', id: 'MO' },
  { name: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', id: 'MK' },
  { name: 'MADAGASCAR', id: 'MG' },
  { name: 'MALAWI', id: 'MW' },
  { name: 'MALAYSIA', id: 'MY' },
  { name: 'MALDIVES', id: 'MV' },
  { name: 'MALI', id: 'ML' },
  { name: 'MALTA', id: 'MT' },
  { name: 'MARSHALL ISLANDS', id: 'MH' },
  { name: 'MARTINIQUE', id: 'MQ' },
  { name: 'MAURITANIA', id: 'MR' },
  { name: 'MAURITIUS', id: 'MU' },
  { name: 'MAYOTTE', id: 'YT' },
  { name: 'MEXICO', id: 'MX' },
  { name: 'MICRONESIA, FEDERATED STATES OF', id: 'FM' },
  { name: 'MOLDOVA, REPUBLIC OF', id: 'MD' },
  { name: 'MONACO', id: 'MC' },
  { name: 'MONGOLIA', id: 'MN' },
  { name: 'MONTENEGRO', id: 'ME' },
  { name: 'MONTSERRAT', id: 'MS' },
  { name: 'MOROCCO', id: 'MA' },
  { name: 'MOZAMBIQUE', id: 'MZ' },
  { name: 'MYANMAR', id: 'MM' },
  { name: 'NAMIBIA', id: 'NA' },
  { name: 'NAURU', id: 'NR' },
  { name: 'NEPAL', id: 'NP' },
  { name: 'NETHERLANDS', id: 'NL' },
  { name: 'NETHERLANDS ANTILLES', id: 'AN' },
  { name: 'NEW CALEDONIA', id: 'NC' },
  { name: 'NEW ZEALAND', id: 'NZ' },
  { name: 'NICARAGUA', id: 'NI' },
  { name: 'NIGER', id: 'NE' },
  { name: 'NIGERIA', id: 'NG' },
  { name: 'NIUE', id: 'NU' },
  { name: 'NORFOLK ISLAND', id: 'NF' },
  { name: 'NORTHERN MARIANA ISLANDS', id: 'MP' },
  { name: 'NORWAY', id: 'NO' },
  { name: 'OMAN', id: 'OM' },
  { name: 'PAKISTAN', id: 'PK' },
  { name: 'PALAU', id: 'PW' },
  { name: 'PALESTINIAN TERRITORY, OCCUPIED', id: 'PS' },
  { name: 'PANAMA', id: 'PA' },
  { name: 'PAPUA NEW GUINEA', id: 'PG' },
  { name: 'PARAGUAY', id: 'PY' },
  { name: 'PERU', id: 'PE' },
  { name: 'PHILIPPINES', id: 'PH' },
  { name: 'PITCAIRN', id: 'PN' },
  { name: 'POLAND', id: 'PL' },
  { name: 'PORTUGAL', id: 'PT' },
  { name: 'PUERTO RICO', id: 'PR' },
  { name: 'QATAR', id: 'QA' },
  { name: 'RÉUNION', id: 'RE' },
  { name: 'ROMANIA', id: 'RO' },
  { name: 'RUSSIAN FEDERATION', id: 'RU' },
  { name: 'RWANDA', id: 'RW' },
  { name: 'SAINT BARTHÉLEMY', id: 'BL' },
  { name: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', id: 'SH' },
  { name: 'SAINT KITTS AND NEVIS', id: 'KN' },
  { name: 'SAINT LUCIA', id: 'LC' },
  { name: 'SAINT MARTIN', id: 'MF' },
  { name: 'SAINT PIERRE AND MIQUELON', id: 'PM' },
  { name: 'SAINT VINCENT AND THE GRENADINES', id: 'VC' },
  { name: 'SAMOA', id: 'WS' },
  { name: 'SAN MARINO', id: 'SM' },
  { name: 'SAO TOME AND PRINCIPE', id: 'ST' },
  { name: 'SAUDI ARABIA', id: 'SA' },
  { name: 'SENEGAL', id: 'SN' },
  { name: 'SERBIA', id: 'RS' },
  { name: 'SEYCHELLES', id: 'SC' },
  { name: 'SIERRA LEONE', id: 'SL' },
  { name: 'SINGAPORE', id: 'SG' },
  { name: 'SLOVAKIA', id: 'SK' },
  { name: 'SLOVENIA', id: 'SI' },
  { name: 'SOLOMON ISLANDS', id: 'SB' },
  { name: 'SOMALIA', id: 'SO' },
  { name: 'SOUTH AFRICA', id: 'ZA' },
  { name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', id: 'GS' },
  { name: 'SPAIN', id: 'ES' },
  { name: 'SRI LANKA', id: 'LK' },
  { name: 'SUDAN', id: 'SD' },
  { name: 'SURINAME', id: 'SR' },
  { name: 'SVALBARD AND JAN MAYEN', id: 'SJ' },
  { name: 'SWAZILAND', id: 'SZ' },
  { name: 'SWEDEN', id: 'SE' },
  { name: 'SWITZERLAND', id: 'CH' },
  { name: 'SYRIAN ARAB REPUBLIC', id: 'SY' },
  { name: 'TAIWAN, PROVINCE OF CHINA', id: 'TW' },
  { name: 'TAJIKISTAN', id: 'TJ' },
  { name: 'TANZANIA, UNITED REPUBLIC OF', id: 'TZ' },
  { name: 'THAILAND', id: 'TH' },
  { name: 'TIMOR-LESTE', id: 'TL' },
  { name: 'TOGO', id: 'TG' },
  { name: 'TOKELAU', id: 'TK' },
  { name: 'TONGA', id: 'TO' },
  { name: 'TRINIDAD AND TOBAGO', id: 'TT' },
  { name: 'TUNISIA', id: 'TN' },
  { name: 'TURKEY', id: 'TR' },
  { name: 'TURKMENISTAN', id: 'TM' },
  { name: 'TURKS AND CAICOS ISLANDS', id: 'TC' },
  { name: 'TUVALU', id: 'TV' },
  { name: 'UGANDA', id: 'UG' },
  { name: 'UKRAINE', id: 'UA' },
  { name: 'UNITED ARAB EMIRATES', id: 'AE' },
  { name: 'UNITED KINGDOM', id: 'GB' },
  { name: 'UNITED STATES', id: 'US' },
  { name: 'UNITED STATES MINOR OUTLYING ISLANDS', id: 'UM' },
  { name: 'URUGUAY', id: 'UY' },
  { name: 'UZBEKISTAN', id: 'UZ' },
  { name: 'VANUATU', id: 'VU' },
  { name: 'VENEZUELA, BOLIVARIAN REPUBLIC OF', id: 'VE' },
  { name: 'VIET NAM', id: 'VN' },
  { name: 'VIRGIN ISLANDS, BRITISH', id: 'VG' },
  { name: 'VIRGIN ISLANDS, U.S.', id: 'VI' },
  { name: 'WALLIS AND FUTUNA', id: 'WF' },
  { name: 'WESTERN SAHARA', id: 'EH' },
  { name: 'YEMEN', id: 'YE' },
  { name: 'ZAMBIA', id: 'ZM' },
  { name: 'ZIMBABWE', id: 'ZW' },
];
