import React from 'react';
import ProductUrl from '../images/pc-slider-temp.jfif';

export const ProductData = [
    {
        id: '#200541',
        productUrl: ProductUrl,
        productName:
            'Summer Activities Chips for Kids (Blue) (V1N-071A-0122-01)',
        qty: '03',
        totalWsp: { wsp: '$10.00', wsp_unit: '$2.00/unit' },
        totalMSRP: { msrp: '$25.00', msrp_unit: '$8.00/unit' },
        fulfillmentStatus: 'Fulfilled',
        shippingCarrier: '-',
        TranckingNumber: '-',
    },
    {
        id: '#200541',
        productUrl: ProductUrl,
        productName:
            'Summer Activities Chips for Kids (Blue) (V1N-071A-0122-01)',
        qty: '03',
        totalWsp: { wsp: '$10.00', wsp_unit: '$2.00/unit' },
        totalMSRP: { msrp: '$25.00', msrp_unit: '$8.00/unit' },
        fulfillmentStatus: 'Unfulfilled',
        shippingCarrier: 'USPS Standard shipping (7-10 bussiness days)',
        TranckingNumber: '54554115',
    },
    {
        id: '#200541',
        productUrl: ProductUrl,
        productName:
            'Summer Activities Chips for Kids (Blue) (V1N-071A-0122-01)',
        qty: '03',
        totalWsp: { wsp: '$10.00', wsp_unit: '$2.00/unit' },
        totalMSRP: { msrp: '$25.00', msrp_unit: '$8.00/unit' },
        fulfillmentStatus: 'Cancelled',
        shippingCarrier: '-',
        TranckingNumber: '-',
    },
    {
        id: '#200541',
        productUrl: ProductUrl,
        productName:
            'Summer Activities Chips for Kids (Blue) (V1N-071A-0122-01)',
        qty: '03',
        totalWsp: { wsp: '$10.00', wsp_unit: '$2.00/unit' },
        totalMSRP: { msrp: '$25.00', msrp_unit: '$8.00/unit' },
        fulfillmentStatus: 'Fulfilled',
        shippingCarrier: '-',
        TranckingNumber: '-',
    },
    {
        id: '#200541',
        productUrl: ProductUrl,
        productName:
            'Summer Activities Chips for Kids (Blue) (V1N-071A-0122-01)',
        qty: '03',
        totalWsp: { wsp: '$10.00', wsp_unit: '$2.00/unit' },
        totalMSRP: { msrp: '$25.00', msrp_unit: '$8.00/unit' },
        fulfillmentStatus: 'Unfulfilled',
        shippingCarrier: '-',
        TranckingNumber: '-',
    },
    {
        id: '#200541',
        productUrl: ProductUrl,
        productName:
            'Summer Activities Chips for Kids (Blue) (V1N-071A-0122-01)',
        qty: '03',
        totalWsp: { wsp: '$10.00', wsp_unit: '$2.00/unit' },
        totalMSRP: { msrp: '$25.00', msrp_unit: '$8.00/unit' },
        fulfillmentStatus: 'Cancelled',
        shippingCarrier: '-',
        TranckingNumber: '-',
    },

    {
        id: '#200542',
        productUrl: ProductUrl,
        productName:
            'Summer Activities Chips for Kids (Blue) (V1N-071A-0122-01)',
        qty: '03',
        totalWsp: { wsp: '$10.00', wsp_unit: '$2.00/unit' },
        totalMSRP: { msrp: '$25.00', msrp_unit: '$8.00/unit' },
        fulfillmentStatus: 'Fulfilled',
        shippingCarrier: '-',
        TranckingNumber: '-',
    },
    {
        id: '#200542',
        productUrl: ProductUrl,
        productName:
            'Summer Activities Chips for Kids (Blue) (V1N-071A-0122-01)',
        qty: '03',
        totalWsp: { wsp: '$10.00', wsp_unit: '$2.00/unit' },
        totalMSRP: { msrp: '$25.00', msrp_unit: '$8.00/unit' },
        fulfillmentStatus: 'Cancelled',
        shippingCarrier: 'USPS Standard shipping (7-10 bussiness days)',
        TranckingNumber: '54554115 54554115 54554115',
    },
    {
        id: '#200542',
        productUrl: ProductUrl,
        productName:
            'Summer Activities Chips for Kids (Blue) (V1N-071A-0122-01)',
        qty: '03',
        totalWsp: { wsp: '$10.00', wsp_unit: '$2.00/unit' },
        totalMSRP: { msrp: '$25.00', msrp_unit: '$8.00/unit' },
        fulfillmentStatus: 'Fulfilled',
        shippingCarrier: '-',
        TranckingNumber: '-',
    },
    {
        id: '#200542',
        productUrl: ProductUrl,
        productName:
            'Summer Activities Chips for Kids (Blue) (V1N-071A-0122-01)',
        qty: '03',
        totalWsp: { wsp: '$10.00', wsp_unit: '$2.00/unit' },
        totalMSRP: { msrp: '$25.00', msrp_unit: '$8.00/unit' },
        fulfillmentStatus: 'Unfulfilled',
        shippingCarrier: '-',
        TranckingNumber: '-',
    },
    {
        id: '#200542',
        productUrl: ProductUrl,
        productName:
            'Summer Activities Chips for Kids (Blue) (V1N-071A-0122-01)',
        qty: '03',
        totalWsp: { wsp: '$10.00', wsp_unit: '$2.00/unit' },
        totalMSRP: { msrp: '$25.00', msrp_unit: '$8.00/unit' },
        fulfillmentStatus: 'Unfulfilled',
        shippingCarrier: '-',
        TranckingNumber: '-',
    },
    {
        id: '#200542',
        productUrl: ProductUrl,
        productName:
            'Summer Activities Chips for Kids (Blue) (V1N-071A-0122-01)',
        qty: '03',
        totalWsp: { wsp: '$10.00', wsp_unit: '$2.00/unit' },
        totalMSRP: { msrp: '$25.00', msrp_unit: '$8.00/unit' },
        fulfillmentStatus: 'Fulfilled',
        shippingCarrier: '-',
        TranckingNumber: '-',
    },
];

export const Data = [
    {
        id: '#200541',
        retailerName: 'Retailer A',
        orderDate: 'Today 01:34 am',
        customerName: 'Jane Doe',
        cutomerOrderId: '#200541',
        qty: '6',
        wsp: '$270.00',
        fees: '$19.20',
    },
    {
        id: '#200542',
        retailerName: 'Retailer B',
        orderDate: 'Today 01:34 am',
        customerName: 'Jane Doe',
        cutomerOrderId: '#200541',
        qty: '6',
        wsp: '$270.00',
        fees: '$19.20',
    },
    {
        id: '#200543',
        retailerName: 'Retailer C',
        orderDate: 'Today 01:34 am',
        customerName: 'Jane Doe',
        cutomerOrderId: '#200541',
        qty: '6',
        wsp: '$270.00',
        fees: '$19.20',
    },
    {
        id: '#200544',
        retailerName: 'Retailer D',
        orderDate: 'Today 01:34 am',
        customerName: 'Jane Doe',
        cutomerOrderId: '#200541',
        qty: '6',
        wsp: '$270.00',
        fees: '$19.20',
    },
    {
        id: '#200545',
        retailerName: 'Retailer E',
        orderDate: 'Today 01:34 am',
        customerName: 'Jane Doe',
        cutomerOrderId: '#200541',
        qty: '6',
        wsp: '$270.00',
        fees: '$19.20',
    },
    {
        id: '#200546',
        retailerName: 'Retailer F',
        orderDate: 'Today 01:34 am',
        customerName: 'Jane Doe',
        cutomerOrderId: '#200541',
        qty: '6',
        wsp: '$270.00',
        fees: '$19.20',
    },
    {
        id: '#200547',
        retailerName: 'Retailer G',
        orderDate: 'Today 01:34 am',
        customerName: 'Jane Doe',
        cutomerOrderId: '#200541',
        qty: '6',
        wsp: '$270.00',
        fees: '$19.20',
    },
    {
        id: '#200548',
        retailerName: 'Retailer H',
        orderDate: 'Today 01:34 am',
        customerName: 'Jane Doe',
        cutomerOrderId: '#200541',
        qty: '6',
        wsp: '$270.00',
        fees: '$19.20',
    },
];
